// <auto-generated />
using ConsoleApp1.Infraestructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleApp1.Migrations
{
    [DbContext(typeof(DDDSample1DbContext))]
    partial class DDDSample1DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.3.23174.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConsoleApp1.Domain.Associacao.Associacao", b =>
                {
                    b.Property<string>("NomeAssociacao")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NomeAssociacao");

                    b.ToTable("Associacao", "dbo");
                });

            modelBuilder.Entity("ConsoleApp1.Domain.Categoria.Categoria", b =>
                {
                    b.Property<string>("TipoCategoria")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoCategoria");

                    b.ToTable("Categoria", "dbo");
                });

            modelBuilder.Entity("ConsoleApp1.Domain.Clube.Clube", b =>
                {
                    b.Property<int>("CodigoClube")
                        .HasColumnType("int");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeAssociacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CodigoClube");

                    b.HasIndex("NomeAssociacao");

                    b.ToTable("Clube", "dbo");
                });

            modelBuilder.Entity("ConsoleApp1.Domain.CodigoPaises.CodigoPaises", b =>
                {
                    b.Property<string>("CodPais")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodPais");

                    b.ToTable("CodigoPaises", "dbo");
                });

            modelBuilder.Entity("ConsoleApp1.Domain.DocumentoIdentificacao.DocIdentificacao", b =>
                {
                    b.Property<int>("NrIdentificacao")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NrIdentificacao");

                    b.ToTable("DocumentoIdentificacao", "dbo");
                });

            modelBuilder.Entity("ConsoleApp1.Domain.Equipa.Equipa", b =>
                {
                    b.Property<int>("IdentificadorEquipa")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("CodigoClube")
                        .HasColumnType("int");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoCategoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TipoGenero")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TipoModalidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdentificadorEquipa");

                    b.HasIndex("CodigoClube");

                    b.HasIndex("TipoCategoria");

                    b.HasIndex("TipoGenero");

                    b.HasIndex("TipoModalidade");

                    b.ToTable("Equipa", "dbo");
                });

            modelBuilder.Entity("ConsoleApp1.Domain.Genero.Genero", b =>
                {
                    b.Property<string>("TipoGenero")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoGenero");

                    b.ToTable("Genero", "dbo");
                });

            modelBuilder.Entity("ConsoleApp1.Domain.InscricaoDefinitivaAssociacaoEquipa.InscricaoDefinitivaAssociacaoEquipa", b =>
                {
                    b.Property<int>("CodOperacao")
                        .HasColumnType("int");

                    b.Property<int>("IdentificadorEquipa")
                        .HasColumnType("int");

                    b.Property<string>("NomeAssociacao")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CodOperacao", "IdentificadorEquipa", "NomeAssociacao");

                    b.HasIndex("CodOperacao")
                        .IsUnique();

                    b.HasIndex("IdentificadorEquipa");

                    b.ToTable("InscricaoDefinitivaAssociacaoEquipa", "dbo");
                });

            modelBuilder.Entity("ConsoleApp1.Domain.InscricaoDefinitivaAssociacaoJogador.InscricaoDefinitivaAssociacaoJogador", b =>
                {
                    b.Property<int>("CodOperacao")
                        .HasColumnType("int");

                    b.Property<int>("Licenca")
                        .HasColumnType("int");

                    b.Property<string>("NomeAssociacao")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CodOperacao", "Licenca", "NomeAssociacao");

                    b.HasIndex("CodOperacao")
                        .IsUnique();

                    b.HasIndex("Licenca");

                    b.ToTable("InscricaoDefinitivaAssociacaoJogador", "dbo");
                });

            modelBuilder.Entity("ConsoleApp1.Domain.InscricaoProvisoriaClubeEquipa.InscricaoProvisoriaClubeEquipa", b =>
                {
                    b.Property<int>("CodOperacao")
                        .HasColumnType("int");

                    b.Property<int>("IdentificadorEquipa")
                        .HasColumnType("int");

                    b.Property<int>("CodigoClube")
                        .HasColumnType("int");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JogadorLicenca")
                        .HasColumnType("int");

                    b.HasKey("CodOperacao", "IdentificadorEquipa", "CodigoClube");

                    b.HasIndex("CodOperacao")
                        .IsUnique();

                    b.HasIndex("CodigoClube");

                    b.HasIndex("IdentificadorEquipa");

                    b.HasIndex("JogadorLicenca");

                    b.ToTable("InscricaoProvisoriaClubeEquipa", "dbo");
                });

            modelBuilder.Entity("ConsoleApp1.Domain.InscricaoProvisoriaClubeJogador.InscricaoProvisoriaClubeJogador", b =>
                {
                    b.Property<int>("CodOperacao")
                        .HasColumnType("int");

                    b.Property<int>("Licenca")
                        .HasColumnType("int");

                    b.Property<int>("CodigoClube")
                        .HasColumnType("int");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodOperacao", "Licenca", "CodigoClube");

                    b.HasIndex("CodOperacao")
                        .IsUnique();

                    b.HasIndex("CodigoClube");

                    b.HasIndex("Licenca");

                    b.ToTable("InscricaoProvisoriaClubeJogador", "dbo");
                });

            modelBuilder.Entity("ConsoleApp1.Domain.Jogador.Jogador", b =>
                {
                    b.Property<int>("Licenca")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdentificadorEquipa")
                        .HasColumnType("int");

                    b.Property<int>("IdentificadorPessoa")
                        .HasColumnType("int");

                    b.HasKey("Licenca");

                    b.HasIndex("IdentificadorEquipa");

                    b.HasIndex("IdentificadorPessoa")
                        .IsUnique();

                    b.ToTable("Jogador", "dbo");
                });

            modelBuilder.Entity("ConsoleApp1.Domain.Modalidade.Modalidade", b =>
                {
                    b.Property<string>("TipoModalidade")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoModalidade");

                    b.ToTable("Modalidade", "dbo");
                });

            modelBuilder.Entity("ConsoleApp1.Domain.Nacionalidade.Nacionalidade", b =>
                {
                    b.Property<string>("NacionalidadePais")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodPaises")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NomePais")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NacionalidadePais");

                    b.HasIndex("NomePais", "CodPaises")
                        .IsUnique();

                    b.ToTable("Nacionalidade", "dbo");
                });

            modelBuilder.Entity("ConsoleApp1.Domain.Pais.Pais", b =>
                {
                    b.Property<string>("NomePais")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NomePais");

                    b.ToTable("Pais", "dbo");
                });

            modelBuilder.Entity("ConsoleApp1.Domain.PaisCodigo.PaisCodigo", b =>
                {
                    b.Property<string>("NomePais")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodPaises")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NomePais", "CodPaises");

                    b.HasIndex("CodPaises");

                    b.ToTable("PaisCodigo", "dbo");
                });

            modelBuilder.Entity("ConsoleApp1.Domain.PaisNascenca.PaisNascenca", b =>
                {
                    b.Property<string>("NascencaPais")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodPaises")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NomePais")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NascencaPais");

                    b.HasIndex("NomePais", "CodPaises")
                        .IsUnique();

                    b.ToTable("PaisNascenca", "dbo");
                });

            modelBuilder.Entity("ConsoleApp1.Domain.Pessoa.Pessoa", b =>
                {
                    b.Property<int>("IdentificadorPessoa")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NacionalidadePais")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NascencaPais")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NrIdentificacao")
                        .HasColumnType("int");

                    b.Property<string>("TipoGenero")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdentificadorPessoa");

                    b.HasIndex("NacionalidadePais")
                        .IsUnique();

                    b.HasIndex("NascencaPais")
                        .IsUnique();

                    b.HasIndex("NrIdentificacao")
                        .IsUnique();

                    b.HasIndex("TipoGenero");

                    b.ToTable("Pessoa", "dbo");
                });

            modelBuilder.Entity("ConsoleApp1.Domain.ProcessoInscricao.ProcessoInscricao", b =>
                {
                    b.Property<int>("CodOperacao")
                        .HasColumnType("int");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodOperacao");

                    b.ToTable("ProcessoInscricao", "dbo");
                });

            modelBuilder.Entity("ConsoleApp1.Domain.Clube.Clube", b =>
                {
                    b.HasOne("ConsoleApp1.Domain.Associacao.Associacao", "Associacao")
                        .WithMany("Clubes")
                        .HasForeignKey("NomeAssociacao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("ConsoleApp1.Domain.Clube.Morada", "Morada", b1 =>
                        {
                            b1.Property<int>("ClubeCodigoClube")
                                .HasColumnType("int");

                            b1.Property<string>("Morad")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ClubeCodigoClube");

                            b1.ToTable("Clube", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ClubeCodigoClube");
                        });

                    b.OwnsOne("ConsoleApp1.Domain.Clube.NifClube", "NifClube", b1 =>
                        {
                            b1.Property<int>("ClubeCodigoClube")
                                .HasColumnType("int");

                            b1.Property<int>("ClubeNif")
                                .HasColumnType("int");

                            b1.HasKey("ClubeCodigoClube");

                            b1.ToTable("Clube", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ClubeCodigoClube");
                        });

                    b.OwnsOne("ConsoleApp1.Domain.Clube.NomeClube", "NomeClube", b1 =>
                        {
                            b1.Property<int>("ClubeCodigoClube")
                                .HasColumnType("int");

                            b1.Property<string>("NomeClub")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ClubeCodigoClube");

                            b1.ToTable("Clube", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ClubeCodigoClube");
                        });

                    b.OwnsOne("ConsoleApp1.Domain.Clube.NrEquipas", "NrEquipas", b1 =>
                        {
                            b1.Property<int>("ClubeCodigoClube")
                                .HasColumnType("int");

                            b1.Property<int>("NumeroEquipas")
                                .HasColumnType("int");

                            b1.HasKey("ClubeCodigoClube");

                            b1.ToTable("Clube", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ClubeCodigoClube");
                        });

                    b.OwnsOne("ConsoleApp1.Domain.Clube.TelefoneClube", "TelefoneClube", b1 =>
                        {
                            b1.Property<int>("ClubeCodigoClube")
                                .HasColumnType("int");

                            b1.Property<string>("TelefoneClub")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ClubeCodigoClube");

                            b1.ToTable("Clube", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ClubeCodigoClube");
                        });

                    b.Navigation("Associacao");

                    b.Navigation("Morada")
                        .IsRequired();

                    b.Navigation("NifClube")
                        .IsRequired();

                    b.Navigation("NomeClube")
                        .IsRequired();

                    b.Navigation("NrEquipas")
                        .IsRequired();

                    b.Navigation("TelefoneClube")
                        .IsRequired();
                });

            modelBuilder.Entity("ConsoleApp1.Domain.DocumentoIdentificacao.DocIdentificacao", b =>
                {
                    b.OwnsOne("ConsoleApp1.Domain.DocumentoIdentificacao.CheckDigit", "CheckDigit", b1 =>
                        {
                            b1.Property<int>("DocIdentificacaoNrIdentificacao")
                                .HasColumnType("int");

                            b1.Property<int>("CheckDig")
                                .HasColumnType("int");

                            b1.HasKey("DocIdentificacaoNrIdentificacao");

                            b1.ToTable("DocumentoIdentificacao", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("DocIdentificacaoNrIdentificacao");
                        });

                    b.OwnsOne("ConsoleApp1.Domain.DocumentoIdentificacao.LetrasDoc", "LetrasDoc", b1 =>
                        {
                            b1.Property<int>("DocIdentificacaoNrIdentificacao")
                                .HasColumnType("int");

                            b1.Property<string>("LetrasDocumento")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("DocIdentificacaoNrIdentificacao");

                            b1.ToTable("DocumentoIdentificacao", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("DocIdentificacaoNrIdentificacao");
                        });

                    b.OwnsOne("ConsoleApp1.Domain.DocumentoIdentificacao.Nif", "Nif", b1 =>
                        {
                            b1.Property<int>("DocIdentificacaoNrIdentificacao")
                                .HasColumnType("int");

                            b1.Property<string>("NumIdFis")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("DocIdentificacaoNrIdentificacao");

                            b1.ToTable("DocumentoIdentificacao", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("DocIdentificacaoNrIdentificacao");
                        });

                    b.OwnsOne("ConsoleApp1.Domain.DocumentoIdentificacao.NrUtente", "NrUtente", b1 =>
                        {
                            b1.Property<int>("DocIdentificacaoNrIdentificacao")
                                .HasColumnType("int");

                            b1.Property<string>("NumUtente")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("DocIdentificacaoNrIdentificacao");

                            b1.ToTable("DocumentoIdentificacao", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("DocIdentificacaoNrIdentificacao");
                        });

                    b.OwnsOne("ConsoleApp1.Domain.DocumentoIdentificacao.ValidadeDoc", "ValidadeDoc", b1 =>
                        {
                            b1.Property<int>("DocIdentificacaoNrIdentificacao")
                                .HasColumnType("int");

                            b1.Property<int>("Ano")
                                .HasColumnType("int");

                            b1.Property<int>("Dia")
                                .HasColumnType("int");

                            b1.Property<int>("Mes")
                                .HasColumnType("int");

                            b1.HasKey("DocIdentificacaoNrIdentificacao");

                            b1.ToTable("DocumentoIdentificacao", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("DocIdentificacaoNrIdentificacao");
                        });

                    b.Navigation("CheckDigit")
                        .IsRequired();

                    b.Navigation("LetrasDoc")
                        .IsRequired();

                    b.Navigation("Nif")
                        .IsRequired();

                    b.Navigation("NrUtente")
                        .IsRequired();

                    b.Navigation("ValidadeDoc")
                        .IsRequired();
                });

            modelBuilder.Entity("ConsoleApp1.Domain.Equipa.Equipa", b =>
                {
                    b.HasOne("ConsoleApp1.Domain.Clube.Clube", "Clube")
                        .WithMany("Equipas")
                        .HasForeignKey("CodigoClube")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConsoleApp1.Domain.Categoria.Categoria", "Categoria")
                        .WithMany("Equipas")
                        .HasForeignKey("TipoCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConsoleApp1.Domain.Genero.Genero", "Genero")
                        .WithMany("Equipa")
                        .HasForeignKey("TipoGenero")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConsoleApp1.Domain.Modalidade.Modalidade", "Modalidade")
                        .WithMany("Equipas")
                        .HasForeignKey("TipoModalidade")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("ConsoleApp1.Domain.Equipa.Divisao", "Divisao", b1 =>
                        {
                            b1.Property<int>("EquipaIdentificadorEquipa")
                                .HasColumnType("int");

                            b1.Property<string>("Div")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("EquipaIdentificadorEquipa");

                            b1.ToTable("Equipa", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("EquipaIdentificadorEquipa");
                        });

                    b.Navigation("Categoria");

                    b.Navigation("Clube");

                    b.Navigation("Divisao")
                        .IsRequired();

                    b.Navigation("Genero");

                    b.Navigation("Modalidade");
                });

            modelBuilder.Entity("ConsoleApp1.Domain.InscricaoDefinitivaAssociacaoEquipa.InscricaoDefinitivaAssociacaoEquipa", b =>
                {
                    b.HasOne("ConsoleApp1.Domain.ProcessoInscricao.ProcessoInscricao", "ProcessoInscricao")
                        .WithOne("InscricaoDefinitivaAssociacaoEquipa")
                        .HasForeignKey("ConsoleApp1.Domain.InscricaoDefinitivaAssociacaoEquipa.InscricaoDefinitivaAssociacaoEquipa", "CodOperacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsoleApp1.Domain.Equipa.Equipa", "Equipa")
                        .WithMany("InscricaoDefinitivaAssociacaoEquipa")
                        .HasForeignKey("IdentificadorEquipa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipa");

                    b.Navigation("ProcessoInscricao");
                });

            modelBuilder.Entity("ConsoleApp1.Domain.InscricaoDefinitivaAssociacaoJogador.InscricaoDefinitivaAssociacaoJogador", b =>
                {
                    b.HasOne("ConsoleApp1.Domain.ProcessoInscricao.ProcessoInscricao", "ProcessoInscricao")
                        .WithOne("InscricaoDefinitivaAssociacaoJogador")
                        .HasForeignKey("ConsoleApp1.Domain.InscricaoDefinitivaAssociacaoJogador.InscricaoDefinitivaAssociacaoJogador", "CodOperacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsoleApp1.Domain.Jogador.Jogador", "Jogador")
                        .WithMany("InscricaoDefinitivaAssociacaoJogador")
                        .HasForeignKey("Licenca")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Jogador");

                    b.Navigation("ProcessoInscricao");
                });

            modelBuilder.Entity("ConsoleApp1.Domain.InscricaoProvisoriaClubeEquipa.InscricaoProvisoriaClubeEquipa", b =>
                {
                    b.HasOne("ConsoleApp1.Domain.ProcessoInscricao.ProcessoInscricao", "ProcessoInscricao")
                        .WithOne("InscricaoProvisoriaClubeEquipa")
                        .HasForeignKey("ConsoleApp1.Domain.InscricaoProvisoriaClubeEquipa.InscricaoProvisoriaClubeEquipa", "CodOperacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsoleApp1.Domain.Clube.Clube", "Clube")
                        .WithMany("InscricaoProvisoriaClubeEquipa")
                        .HasForeignKey("CodigoClube")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConsoleApp1.Domain.Equipa.Equipa", "Equipa")
                        .WithMany("InscricaoProvisoriaClubeEquipa")
                        .HasForeignKey("IdentificadorEquipa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConsoleApp1.Domain.Jogador.Jogador", "Jogador")
                        .WithMany()
                        .HasForeignKey("JogadorLicenca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clube");

                    b.Navigation("Equipa");

                    b.Navigation("Jogador");

                    b.Navigation("ProcessoInscricao");
                });

            modelBuilder.Entity("ConsoleApp1.Domain.InscricaoProvisoriaClubeJogador.InscricaoProvisoriaClubeJogador", b =>
                {
                    b.HasOne("ConsoleApp1.Domain.ProcessoInscricao.ProcessoInscricao", "ProcessoInscricao")
                        .WithOne("InscricaoProvisoriaClubeJogador")
                        .HasForeignKey("ConsoleApp1.Domain.InscricaoProvisoriaClubeJogador.InscricaoProvisoriaClubeJogador", "CodOperacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsoleApp1.Domain.Clube.Clube", "Clube")
                        .WithMany("InscricaoProvisoriaClubeJogador")
                        .HasForeignKey("CodigoClube")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConsoleApp1.Domain.Jogador.Jogador", "Jogador")
                        .WithMany("InscricaoProvisoriaClubeJogador")
                        .HasForeignKey("Licenca")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clube");

                    b.Navigation("Jogador");

                    b.Navigation("ProcessoInscricao");
                });

            modelBuilder.Entity("ConsoleApp1.Domain.Jogador.Jogador", b =>
                {
                    b.HasOne("ConsoleApp1.Domain.Equipa.Equipa", "Equipa")
                        .WithMany("Jogadores")
                        .HasForeignKey("IdentificadorEquipa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConsoleApp1.Domain.Pessoa.Pessoa", "Pessoa")
                        .WithOne("Jogador")
                        .HasForeignKey("ConsoleApp1.Domain.Jogador.Jogador", "IdentificadorPessoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("ConsoleApp1.Domain.Jogador.EstatutoFpF", "EstatutoFpF", b1 =>
                        {
                            b1.Property<int>("JogadorLicenca")
                                .HasColumnType("int");

                            b1.Property<string>("Estatuto")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("JogadorLicenca");

                            b1.ToTable("Jogador", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("JogadorLicenca");
                        });

                    b.Navigation("Equipa");

                    b.Navigation("EstatutoFpF")
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("ConsoleApp1.Domain.Nacionalidade.Nacionalidade", b =>
                {
                    b.HasOne("ConsoleApp1.Domain.PaisCodigo.PaisCodigo", "PaisCodigo")
                        .WithOne("Nacionalidade")
                        .HasForeignKey("ConsoleApp1.Domain.Nacionalidade.Nacionalidade", "NomePais", "CodPaises")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PaisCodigo");
                });

            modelBuilder.Entity("ConsoleApp1.Domain.PaisCodigo.PaisCodigo", b =>
                {
                    b.HasOne("ConsoleApp1.Domain.CodigoPaises.CodigoPaises", "CodigoPaises")
                        .WithMany("PaisCodigo")
                        .HasForeignKey("CodPaises")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsoleApp1.Domain.Pais.Pais", "Pais")
                        .WithMany("PaisCodigo")
                        .HasForeignKey("NomePais")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodigoPaises");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("ConsoleApp1.Domain.PaisNascenca.PaisNascenca", b =>
                {
                    b.HasOne("ConsoleApp1.Domain.PaisCodigo.PaisCodigo", "PaisCodigo")
                        .WithOne("PaisNascenca")
                        .HasForeignKey("ConsoleApp1.Domain.PaisNascenca.PaisNascenca", "NomePais", "CodPaises")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PaisCodigo");
                });

            modelBuilder.Entity("ConsoleApp1.Domain.Pessoa.Pessoa", b =>
                {
                    b.HasOne("ConsoleApp1.Domain.Nacionalidade.Nacionalidade", "Nacionalidade")
                        .WithOne("Pessoa")
                        .HasForeignKey("ConsoleApp1.Domain.Pessoa.Pessoa", "NacionalidadePais")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsoleApp1.Domain.PaisNascenca.PaisNascenca", "PaisNascenca")
                        .WithOne("Pessoa")
                        .HasForeignKey("ConsoleApp1.Domain.Pessoa.Pessoa", "NascencaPais")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsoleApp1.Domain.DocumentoIdentificacao.DocIdentificacao", "DocIdentificacao")
                        .WithOne("Pessoa")
                        .HasForeignKey("ConsoleApp1.Domain.Pessoa.Pessoa", "NrIdentificacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsoleApp1.Domain.Genero.Genero", "Genero")
                        .WithMany("Pessoa")
                        .HasForeignKey("TipoGenero")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("ConsoleApp1.Domain.Pessoa.ConcelhoResidência", "ConcelhoResidência", b1 =>
                        {
                            b1.Property<int>("PessoaIdentificadorPessoa")
                                .HasColumnType("int");

                            b1.Property<string>("Concelho")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PessoaIdentificadorPessoa");

                            b1.ToTable("Pessoa", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("PessoaIdentificadorPessoa");
                        });

                    b.OwnsOne("ConsoleApp1.Domain.Pessoa.DataNascimento", "DataNascimento", b1 =>
                        {
                            b1.Property<int>("PessoaIdentificadorPessoa")
                                .HasColumnType("int");

                            b1.Property<string>("DataNasc")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PessoaIdentificadorPessoa");

                            b1.ToTable("Pessoa", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("PessoaIdentificadorPessoa");
                        });

                    b.OwnsOne("ConsoleApp1.Domain.Pessoa.Email", "Email", b1 =>
                        {
                            b1.Property<int>("PessoaIdentificadorPessoa")
                                .HasColumnType("int");

                            b1.Property<string>("Emaill")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PessoaIdentificadorPessoa");

                            b1.ToTable("Pessoa", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("PessoaIdentificadorPessoa");
                        });

                    b.OwnsOne("ConsoleApp1.Domain.Pessoa.Nome", "Nome", b1 =>
                        {
                            b1.Property<int>("PessoaIdentificadorPessoa")
                                .HasColumnType("int");

                            b1.Property<string>("Nomee")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PessoaIdentificadorPessoa");

                            b1.ToTable("Pessoa", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("PessoaIdentificadorPessoa");
                        });

                    b.OwnsOne("ConsoleApp1.Domain.Pessoa.Telefone", "Telefone", b1 =>
                        {
                            b1.Property<int>("PessoaIdentificadorPessoa")
                                .HasColumnType("int");

                            b1.Property<string>("Telemovel")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PessoaIdentificadorPessoa");

                            b1.ToTable("Pessoa", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("PessoaIdentificadorPessoa");
                        });

                    b.Navigation("ConcelhoResidência")
                        .IsRequired();

                    b.Navigation("DataNascimento")
                        .IsRequired();

                    b.Navigation("DocIdentificacao");

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Genero");

                    b.Navigation("Nacionalidade");

                    b.Navigation("Nome")
                        .IsRequired();

                    b.Navigation("PaisNascenca");

                    b.Navigation("Telefone")
                        .IsRequired();
                });

            modelBuilder.Entity("ConsoleApp1.Domain.ProcessoInscricao.ProcessoInscricao", b =>
                {
                    b.OwnsOne("ConsoleApp1.Domain.ProcessoInscricao.DataRegisto", "DataRegisto", b1 =>
                        {
                            b1.Property<int>("ProcessoInscricaoCodOperacao")
                                .HasColumnType("int");

                            b1.Property<string>("DataReg")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ProcessoInscricaoCodOperacao");

                            b1.ToTable("ProcessoInscricao", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ProcessoInscricaoCodOperacao");
                        });

                    b.OwnsOne("ConsoleApp1.Domain.ProcessoInscricao.DataSubscricao", "DataSubscricao", b1 =>
                        {
                            b1.Property<int>("ProcessoInscricaoCodOperacao")
                                .HasColumnType("int");

                            b1.Property<string>("DataSubs")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ProcessoInscricaoCodOperacao");

                            b1.ToTable("ProcessoInscricao", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ProcessoInscricaoCodOperacao");
                        });

                    b.OwnsOne("ConsoleApp1.Domain.ProcessoInscricao.EpocaDesportiva", "EpocaDesportiva", b1 =>
                        {
                            b1.Property<int>("ProcessoInscricaoCodOperacao")
                                .HasColumnType("int");

                            b1.Property<string>("EpocaDesp")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ProcessoInscricaoCodOperacao");

                            b1.ToTable("ProcessoInscricao", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ProcessoInscricaoCodOperacao");
                        });

                    b.OwnsOne("ConsoleApp1.Domain.ProcessoInscricao.Estado", "Estado", b1 =>
                        {
                            b1.Property<int>("ProcessoInscricaoCodOperacao")
                                .HasColumnType("int");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ProcessoInscricaoCodOperacao");

                            b1.ToTable("ProcessoInscricao", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ProcessoInscricaoCodOperacao");
                        });

                    b.OwnsOne("ConsoleApp1.Domain.ProcessoInscricao.TipoProcesso", "TipoProcesso", b1 =>
                        {
                            b1.Property<int>("ProcessoInscricaoCodOperacao")
                                .HasColumnType("int");

                            b1.Property<string>("ProcessoTipo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ProcessoInscricaoCodOperacao");

                            b1.ToTable("ProcessoInscricao", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ProcessoInscricaoCodOperacao");
                        });

                    b.Navigation("DataRegisto")
                        .IsRequired();

                    b.Navigation("DataSubscricao")
                        .IsRequired();

                    b.Navigation("EpocaDesportiva")
                        .IsRequired();

                    b.Navigation("Estado")
                        .IsRequired();

                    b.Navigation("TipoProcesso")
                        .IsRequired();
                });

            modelBuilder.Entity("ConsoleApp1.Domain.Associacao.Associacao", b =>
                {
                    b.Navigation("Clubes");
                });

            modelBuilder.Entity("ConsoleApp1.Domain.Categoria.Categoria", b =>
                {
                    b.Navigation("Equipas");
                });

            modelBuilder.Entity("ConsoleApp1.Domain.Clube.Clube", b =>
                {
                    b.Navigation("Equipas");

                    b.Navigation("InscricaoProvisoriaClubeEquipa");

                    b.Navigation("InscricaoProvisoriaClubeJogador");
                });

            modelBuilder.Entity("ConsoleApp1.Domain.CodigoPaises.CodigoPaises", b =>
                {
                    b.Navigation("PaisCodigo");
                });

            modelBuilder.Entity("ConsoleApp1.Domain.DocumentoIdentificacao.DocIdentificacao", b =>
                {
                    b.Navigation("Pessoa")
                        .IsRequired();
                });

            modelBuilder.Entity("ConsoleApp1.Domain.Equipa.Equipa", b =>
                {
                    b.Navigation("InscricaoDefinitivaAssociacaoEquipa");

                    b.Navigation("InscricaoProvisoriaClubeEquipa");

                    b.Navigation("Jogadores");
                });

            modelBuilder.Entity("ConsoleApp1.Domain.Genero.Genero", b =>
                {
                    b.Navigation("Equipa");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("ConsoleApp1.Domain.Jogador.Jogador", b =>
                {
                    b.Navigation("InscricaoDefinitivaAssociacaoJogador");

                    b.Navigation("InscricaoProvisoriaClubeJogador");
                });

            modelBuilder.Entity("ConsoleApp1.Domain.Modalidade.Modalidade", b =>
                {
                    b.Navigation("Equipas");
                });

            modelBuilder.Entity("ConsoleApp1.Domain.Nacionalidade.Nacionalidade", b =>
                {
                    b.Navigation("Pessoa")
                        .IsRequired();
                });

            modelBuilder.Entity("ConsoleApp1.Domain.Pais.Pais", b =>
                {
                    b.Navigation("PaisCodigo");
                });

            modelBuilder.Entity("ConsoleApp1.Domain.PaisCodigo.PaisCodigo", b =>
                {
                    b.Navigation("Nacionalidade")
                        .IsRequired();

                    b.Navigation("PaisNascenca")
                        .IsRequired();
                });

            modelBuilder.Entity("ConsoleApp1.Domain.PaisNascenca.PaisNascenca", b =>
                {
                    b.Navigation("Pessoa")
                        .IsRequired();
                });

            modelBuilder.Entity("ConsoleApp1.Domain.Pessoa.Pessoa", b =>
                {
                    b.Navigation("Jogador")
                        .IsRequired();
                });

            modelBuilder.Entity("ConsoleApp1.Domain.ProcessoInscricao.ProcessoInscricao", b =>
                {
                    b.Navigation("InscricaoDefinitivaAssociacaoEquipa")
                        .IsRequired();

                    b.Navigation("InscricaoDefinitivaAssociacaoJogador")
                        .IsRequired();

                    b.Navigation("InscricaoProvisoriaClubeEquipa")
                        .IsRequired();

                    b.Navigation("InscricaoProvisoriaClubeJogador")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
