DROP TABLE Pessoa;
DROP TABLE Equipa;
DROP TABLE Clube;
DROP TABLE Associacao;
DROP TABLE DocumentoIdentificacao;
DROP TABLE Jogador;
DROP TABLE Arbitro;
DROP TABLE Categoria;
DROP TABLE Modalidade;
DROP TABLE Genero;
DROP TABLE PaisNascenca;
DROP TABLE CodigoPais;
DROP TABLE Nacionalidade;
DROP TABLE InscricaoProvisoriaClubeJogador;
DROP TABLE InscricaoDefinitivaAssociacaoJogador;
DROP TABLE Processo;
DROP TABLE InscricaoDefinitivaAssociacaoEquipa;
DROP TABLE InscricaoProvisoriaClubeEquipa;
DROP TABLE Pais;
DROP TABLE CodigoPaises;


CREATE TABLE Pessoa (idPessoa int IDENTITY NOT NULL, foto image NULL, nome varchar(255) NOT NULL, dataNascimento date NOT NULL, dataRegisto int NOT NULL, telefone int NULL UNIQUE, email varchar(255) NULL UNIQUE, concelhoResidencia varchar(255) NULL, dataModificacao date NULL, dataEliminacao date NULL, tipoGenero varchar(255) NOT NULL, docId int NOT NULL, nascencaPais varchar(255) NOT NULL, nacionalidadePais varchar(255) NOT NULL);
CREATE TABLE Equipa (idEquipa int IDENTITY NOT NULL, divisao varchar(255) NOT NULL, codClube int NOT NULL, tipoCategoria varchar(255) NOT NULL, tipoModalidade varchar(255) NOT NULL, tipoGenero varchar(255) NOT NULL);
CREATE TABLE Clube (codClube int IDENTITY NOT NULL, nomeClube varchar(255) NOT NULL UNIQUE, nifClube int NOT NULL UNIQUE, nrEquipas int NOT NULL, telefoneClube int NOT NULL, logotipo image NULL, morada varchar(255) NULL, nomeAssociacao varchar(255) NOT NULL);
CREATE TABLE Associacao (nomeAssociacao varchar(255) NOT NULL);
CREATE TABLE DocumentoIdentificacao (nrIdentificacao int IDENTITY NOT NULL, tipoDocumento varchar(255) NULL, letrasDoc varchar(255) NOT NULL, checkDigit char(255) NOT NULL, validadeDoc date NOT NULL, nifId int NULL UNIQUE, nrUtente int NULL);
CREATE TABLE Jogador (licencaFpf int IDENTITY NOT NULL, estatutoFpf varchar(255) NOT NULL, idPessoa int NOT NULL, idEquipa int NOT NULL);
CREATE TABLE Arbitro (nrLicenca int IDENTITY NOT NULL, idPessoa int NOT NULL);
CREATE TABLE Categoria (tipoCategoria varchar(255) NOT NULL);
CREATE TABLE Modalidade (tipoModalidade varchar(255) NOT NULL);
CREATE TABLE Genero (tipoGenero varchar(255) NOT NULL);
CREATE TABLE PaisNascenca (nascencaPais varchar(255) NOT NULL, nomePais varchar(255) NOT NULL, codigoPais int NOT NULL);
CREATE TABLE CodigoPais (codigoPais int NOT NULL, nomePais varchar(255) NOT NULL);
CREATE TABLE Nacionalidade (nacionalidadePais varchar(255) NOT NULL, nomePais varchar(255) NOT NULL, codigoPais int NOT NULL);
CREATE TABLE InscricaoProvisoriaClubeJogador (codOperacao int NOT NULL, codClube int NOT NULL, licencaFpf int NOT NULL, dataSubscricao date NOT NULL);
CREATE TABLE InscricaoDefinitivaAssociacaoJogador (codOperacao int NOT NULL, nomeAssociacao varchar(255) NOT NULL, licencaFpf int NOT NULL);
CREATE TABLE Processo (codOperacao int IDENTITY NOT NULL, nrProcesso int NOT NULL, tipoProcesso varchar(255) NOT NULL, estado varchar(255) NULL, epocaDesportiva varchar(255) NOT NULL, dataRegisto date NULL, capturaFotografica image NULL);
CREATE TABLE InscricaoDefinitivaAssociacaoEquipa (nomeAssociacao varchar(255) NOT NULL, idEquipa int NOT NULL, codOperacao int NOT NULL);
CREATE TABLE InscricaoProvisoriaClubeEquipa (codOperacao int NOT NULL, codClube int NOT NULL, idEquipa int NOT NULL, dataSubscricao date NULL);
CREATE TABLE Pais (nomePais varchar(255) NOT NULL);
CREATE TABLE CodigoPaises (codigoPais int IDENTITY NOT NULL);

ALTER TABLE Pessoa ADD PRIMARY KEY (idPessoa);
ALTER TABLE Equipa ADD PRIMARY KEY (idEquipa);
ALTER TABLE Clube ADD PRIMARY KEY (codClube);
ALTER TABLE Associacao ADD PRIMARY KEY (nomeAssociacao);
ALTER TABLE DocumentoIdentificacao ADD PRIMARY KEY (nrIdentificacao);
ALTER TABLE Jogador ADD PRIMARY KEY (id);
ALTER TABLE Arbitro ADD PRIMARY KEY (nrLicenca);
ALTER TABLE Categoria ADD PRIMARY KEY (tipoCategoria);
ALTER TABLE Modalidade ADD PRIMARY KEY (tipoModalidade);
ALTER TABLE Genero ADD PRIMARY KEY (tipoGenero);
ALTER TABLE PaisNascenca ADD PRIMARY KEY (nascencaPais);
ALTER TABLE CodigoPais ADD PRIMARY KEY (codigoPais, nomePais);
ALTER TABLE Nacionalidade ADD PRIMARY KEY (nacionalidadePais);
ALTER TABLE InscricaoProvisoriaClubeJogador ADD PRIMARY KEY (codOperacao, codClube, licencaFpf);
ALTER TABLE InscricaoDefinitivaAssociacaoJogador ADD PRIMARY KEY (codOperacao, nomeAssociacao, licencaFpf);
ALTER TABLE Processo ADD PRIMARY KEY (codOperacao);
ALTER TABLE InscricaoDefinitivaAssociacaoEquipa ADD PRIMARY KEY (nomeAssociacao, idEquipa, codOperacao);
ALTER TABLE InscricaoProvisoriaClubeEquipa ADD PRIMARY KEY (codOperacao, codClube, idEquipa);
ALTER TABLE Pais ADD PRIMARY KEY (nomePais);
ALTER TABLE CodigoPaises ADD PRIMARY KEY (codigoPais);

ALTER TABLE Clube DROP CONSTRAINT FKClube227645;
ALTER TABLE Equipa DROP CONSTRAINT FKEquipa266221;
ALTER TABLE Jogador DROP CONSTRAINT FKJogador280411;
ALTER TABLE Arbitro DROP CONSTRAINT FKArbitro206200;
ALTER TABLE Equipa DROP CONSTRAINT FKEquipa33960;
ALTER TABLE Equipa DROP CONSTRAINT FKEquipa76758;
ALTER TABLE Equipa DROP CONSTRAINT FKEquipa602589;
ALTER TABLE Pessoa DROP CONSTRAINT FKPessoa256975;
ALTER TABLE Jogador DROP CONSTRAINT FKJogador914281;
ALTER TABLE Pessoa DROP CONSTRAINT FKPessoa813879;
ALTER TABLE Pessoa DROP CONSTRAINT FKPessoa450244;
ALTER TABLE PaisNascenca DROP CONSTRAINT FKPaisNascen982106;
ALTER TABLE Nacionalidade DROP CONSTRAINT FKNacionalid188659;
ALTER TABLE Pessoa DROP CONSTRAINT FKPessoa431814;
ALTER TABLE InscricaoProvisoriaClubeJogador DROP CONSTRAINT FKInscricaoP166029;
ALTER TABLE InscricaoProvisoriaClubeJogador DROP CONSTRAINT FKInscricaoP879463;
ALTER TABLE InscricaoDefinitivaAssociacaoJogador DROP CONSTRAINT FKInscricaoD165948;
ALTER TABLE InscricaoDefinitivaAssociacaoJogador DROP CONSTRAINT FKInscricaoD220829;
ALTER TABLE InscricaoProvisoriaClubeJogador DROP CONSTRAINT FKInscricaoP855851;
ALTER TABLE InscricaoDefinitivaAssociacaoJogador DROP CONSTRAINT FKInscricaoD197217;
ALTER TABLE InscricaoDefinitivaAssociacaoEquipa DROP CONSTRAINT FKInscricaoD45589;
ALTER TABLE InscricaoDefinitivaAssociacaoEquipa DROP CONSTRAINT FKInscricaoD318794;
ALTER TABLE InscricaoDefinitivaAssociacaoEquipa DROP CONSTRAINT FKInscricaoD76858;
ALTER TABLE InscricaoProvisoriaClubeEquipa DROP CONSTRAINT FKInscricaoP676916;
ALTER TABLE InscricaoProvisoriaClubeEquipa DROP CONSTRAINT FKInscricaoP987093;
ALTER TABLE InscricaoProvisoriaClubeEquipa DROP CONSTRAINT FKInscricaoP718735;
ALTER TABLE CodigoPais DROP CONSTRAINT FKCodigoPais581048;
ALTER TABLE CodigoPais DROP CONSTRAINT FKCodigoPais995365;
ALTER TABLE Clube ADD CONSTRAINT FKClube227645 FOREIGN KEY (nomeAssociacao) REFERENCES Associacao (nomeAssociacao);
ALTER TABLE Equipa ADD CONSTRAINT FKEquipa266221 FOREIGN KEY (codClube) REFERENCES Clube (codClube);
ALTER TABLE Jogador ADD CONSTRAINT FKJogador280411 FOREIGN KEY (idPessoa) REFERENCES Pessoa (idPessoa);
ALTER TABLE Arbitro ADD CONSTRAINT FKArbitro206200 FOREIGN KEY (idPessoa) REFERENCES Pessoa (idPessoa);
ALTER TABLE Equipa ADD CONSTRAINT FKEquipa33960 FOREIGN KEY (tipoCategoria) REFERENCES Categoria (tipoCategoria);
ALTER TABLE Equipa ADD CONSTRAINT FKEquipa76758 FOREIGN KEY (tipoModalidade) REFERENCES Modalidade (tipoModalidade);
ALTER TABLE Equipa ADD CONSTRAINT FKEquipa602589 FOREIGN KEY (tipoGenero) REFERENCES Genero (tipoGenero);
ALTER TABLE Pessoa ADD CONSTRAINT FKPessoa256975 FOREIGN KEY (docId) REFERENCES DocumentoIdentificacao (nrIdentificacao);
ALTER TABLE Jogador ADD CONSTRAINT FKJogador914281 FOREIGN KEY (idEquipa) REFERENCES Equipa (idEquipa);
ALTER TABLE Pessoa ADD CONSTRAINT FKPessoa813879 FOREIGN KEY (tipoGenero) REFERENCES Genero (tipoGenero);
ALTER TABLE Pessoa ADD CONSTRAINT FKPessoa450244 FOREIGN KEY (nascencaPais) REFERENCES PaisNascenca (nascencaPais);
ALTER TABLE PaisNascenca ADD CONSTRAINT FKPaisNascen982106 FOREIGN KEY (codigoPais, nomePais) REFERENCES CodigoPais (codigoPais, nomePais);
ALTER TABLE Nacionalidade ADD CONSTRAINT FKNacionalid188659 FOREIGN KEY (codigoPais, nomePais) REFERENCES CodigoPais (codigoPais, nomePais);
ALTER TABLE Pessoa ADD CONSTRAINT FKPessoa431814 FOREIGN KEY (nacionalidadePais) REFERENCES Nacionalidade (nacionalidadePais);
ALTER TABLE InscricaoProvisoriaClubeJogador ADD CONSTRAINT FKInscricaoP166029 FOREIGN KEY (codClube) REFERENCES Clube (codClube);
ALTER TABLE InscricaoProvisoriaClubeJogador ADD CONSTRAINT FKInscricaoP879463 FOREIGN KEY (licencaFpf) REFERENCES Jogador (licencaFpf);
ALTER TABLE InscricaoDefinitivaAssociacaoJogador ADD CONSTRAINT FKInscricaoD165948 FOREIGN KEY (nomeAssociacao) REFERENCES Associacao (nomeAssociacao);
ALTER TABLE InscricaoDefinitivaAssociacaoJogador ADD CONSTRAINT FKInscricaoD220829 FOREIGN KEY (licencaFpf) REFERENCES Jogador (licencaFpf);
ALTER TABLE InscricaoProvisoriaClubeJogador ADD CONSTRAINT FKInscricaoP855851 FOREIGN KEY (codOperacao) REFERENCES Processo (codOperacao);
ALTER TABLE InscricaoDefinitivaAssociacaoJogador ADD CONSTRAINT FKInscricaoD197217 FOREIGN KEY (codOperacao) REFERENCES Processo (codOperacao);
ALTER TABLE InscricaoDefinitivaAssociacaoEquipa ADD CONSTRAINT FKInscricaoD45589 FOREIGN KEY (nomeAssociacao) REFERENCES Associacao (nomeAssociacao);
ALTER TABLE InscricaoDefinitivaAssociacaoEquipa ADD CONSTRAINT FKInscricaoD318794 FOREIGN KEY (idEquipa) REFERENCES Equipa (idEquipa);
ALTER TABLE InscricaoDefinitivaAssociacaoEquipa ADD CONSTRAINT FKInscricaoD76858 FOREIGN KEY (codOperacao) REFERENCES Processo (codOperacao);
ALTER TABLE InscricaoProvisoriaClubeEquipa ADD CONSTRAINT FKInscricaoP676916 FOREIGN KEY (codOperacao) REFERENCES Processo (codOperacao);
ALTER TABLE InscricaoProvisoriaClubeEquipa ADD CONSTRAINT FKInscricaoP987093 FOREIGN KEY (codClube) REFERENCES Clube (codClube);
ALTER TABLE InscricaoProvisoriaClubeEquipa ADD CONSTRAINT FKInscricaoP718735 FOREIGN KEY (idEquipa) REFERENCES Equipa (idEquipa);
ALTER TABLE CodigoPais ADD CONSTRAINT FKCodigoPais581048 FOREIGN KEY (codigoPais) REFERENCES CodigoPaises (codigoPais);
ALTER TABLE CodigoPais ADD CONSTRAINT FKCodigoPais995365 FOREIGN KEY (nomePais) REFERENCES Pais (nomePais);
